// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Job struct {
	JobID       string
	Status      string
	S3InputUrl  string
	S3OutputUrl sql.NullString
	CreatedAt   sql.NullTime
}
