// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const createJob = `-- name: CreateJob :exec
INSERT INTO jobs (job_id, status, s3_input_url)
VALUES ($1, $2, $3)
`

type CreateJobParams struct {
	JobID      string
	Status     string
	S3InputUrl string
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) error {
	_, err := q.db.ExecContext(ctx, createJob, arg.JobID, arg.Status, arg.S3InputUrl)
	return err
}

const getJobStatus = `-- name: GetJobStatus :one
SELECT status 
FROM jobs 
WHERE job_id = $1
`

func (q *Queries) GetJobStatus(ctx context.Context, jobID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getJobStatus, jobID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const updateJobStatus = `-- name: UpdateJobStatus :exec
UPDATE jobs 
SET status = $1, s3_output_url = $2 
WHERE job_id = $3
`

type UpdateJobStatusParams struct {
	Status      string
	S3OutputUrl sql.NullString
	JobID       string
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateJobStatus, arg.Status, arg.S3OutputUrl, arg.JobID)
	return err
}
