version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  go-gateway:
    build: ./go-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - shared-pdf:/app/outputs
      - shared-uploads:/app/uploads

  python-worker:
    build: ./python-worker
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    volumes:
      - shared-pdf:/app/outputs
      - shared-uploads:/app/uploads

volumes:
  shared-pdf:
  shared-uploads: